"""add_notifications_table

Revision ID: 7646b18b7693
Revises: 1dcea3448c64
Create Date: 2025-09-02 17:14:32.210934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7646b18b7693'
down_revision: Union[str, Sequence[str], None] = '1dcea3448c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('connection_request', 'connection_accepted', 'connection_rejected', 'new_message', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_request_id', sa.Integer(), nullable=True),
    sa.Column('related_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['connection_requests.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
